### ISSUE TITLE
cobalt for the web

### ISSUE THREAD

**Issue by lduboeuf** [cobaltians/Cobalt#122] opened 2016-06-13 18:05 UTC
What would be nice i think is that cobalt give you the possibility to build an app for the web.
With an iframe it will be possible to simulate navigation between html views. Maybe not a good practice ?

**Comment by ggendre** [comment] 2016-06-14 06:45
duplicate of #63 and planned for 0.7 :)

**Comment by ggendre** [comment] 2016-06-14 06:46
but thanks anyway :)

**Closed by ggendre** 2016-06-14 06:45 UTC
